# comment

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: portfolioerp-api-container

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}

      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}

      SeedAdmin__Username: ${SEED_ADMIN_USERNAME}
      SeedAdmin__Email: ${SEED_ADMIN_EMAIL}
      SeedAdmin__Password: ${SEED_ADMIN_PASSWORD}