name: .NET CI

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore backend/PortfolioERP_BackEnd.slnx

      - name: Build
        run: dotnet build backend/PortfolioERP_BackEnd.slnx --no-restore

      - name: Run tests
        run: dotnet test backend/PortfolioERP_BackEnd.slnx --no-build
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/portfolioerp-api:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/portfolioerp-api:latest
