name: .NET CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore backend/PortfolioERP_BackEnd.slnx

      - name: Build
        run: dotnet build backend/PortfolioERP_BackEnd.slnx --no-restore

      - name: Run tests
        run: dotnet test backend/PortfolioERP_BackEnd.slnx --no-build